### ISSUE TITLE
Galgenmännchen

### ISSUE THREAD

**Issue by Roj-Sa** [ogruendel/THWS#1]
Hallo, 
würden Sie Ihre Lösungen von der Lektion 18 Prog 2 auch hochladen?
Es wäre sehr hilfreich.
Vielen Dank im Voraus!

**Comment by ogruendel** [comment]
Hallo @Roj-Sa,
die Netzwerkgalgenmännchen Aufgabe ist mit commit 017cbe2 verfügbar.
